FROM python:3.9
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY ./app /code/app
COPY ./tests.sh /code/tests.sh
RUN ["chmod", "+x", "/code/tests.sh"]
ENTRYPOINT ["/bin/sh","/code/tests.sh"]
CMD tail -f /dev/null